#!/bin/bash

echo 

" ____            __                  _   _      _ _            ____                                 _   _____                _        ____ ___ 
 |  _ \ ___ _ __ / _| ___   ___ ___  | | | | ___| (_)_  __     / ___|___  _ __ ___    __ _ _ __   __| | |_   _| __ __ ___   _(_)___   / ___|_ _|
 | |_) / _ \ '__| |_ / _ \ / __/ _ \ | |_| |/ _ \ | \ \/ /____| |   / _ \| '__/ _ \  / _` | '_ \ / _` |   | || '__/ _` \ \ / / / __| | |    | | 
 |  __/  __/ |  |  _| (_) | (_|  __/ |  _  |  __/ | |>  <_____| |__| (_) | | |  __/ | (_| | | | | (_| |   | || | | (_| |\ V /| \__ \ | |___ | | 
 |_|   \___|_|  |_|  \___/ \___\___| |_| |_|\___|_|_/_/\_\     \____\___/|_|  \___|  \__,_|_| |_|\__,_|   |_||_|  \__,_| \_/ |_|___/  \____|___|
                                                                                                                                               "

  echo "Travis CI/Perfore-Helix shell script beginning" 
  wget -q https://package.perforce.com/perforce.pubkey -O - | sudo apt-key add -"
  "echo" done...
 "echo 'deb http://package.perforce.com/apt/ubuntu precise release' | sudo tee -a /etc/apt/sources.list"
   "echo" done...
 "echo 'deb https://packagecloud.io/github/git-lfs/debian/ jessie main' | sudo tee -a /etc/apt/sources.list"
   "echo" done...
 "sudo apt-get install linuxbrew-wrapper"
   "echo" done...
 "sudo apt-get update -qq"
   "echo" done...
 "sudo apt-get install helix-p4d"
   "echo" done...
 "sudo apt-get install -y apt-transport-https"
   "echo" done...
 "sudo systemctl enable helix-p4dctl"
   "echo" done...
 "sudo systemctl start helix-p4dctl"
   "echo" done...
 "sudo /opt/perforce/sbin/configure-helix-p4d.sh -n perforce1 -p ssl:1666 -r /opt/perforce/servers/perforce1 -u montana -P REinforce --unicode"
   "echo" done...
 "p4 info"
   "echo" done...
 "p4 branches"
   "echo" done...
 "p4 -V" 
   "echo" done...
 "p4 -h"
   "echo" done...
 "p4 -size" 
   "echo" done...
 "p4 -where'
   "echo" done...
