#!/bin/bash set -x                                                                                                                                               "

  echo "Travis CI/Perfore-Helix shell script beginning" 
  wget -q https://package.perforce.com/perforce.pubkey -O - | sudo apt-key add -"
  "echo" done...
 "echo 'deb http://package.perforce.com/apt/ubuntu precise release' | sudo tee -a /etc/apt/sources.list"
   "echo" done...
 "echo 'deb https://packagecloud.io/github/git-lfs/debian/ jessie main' | sudo tee -a /etc/apt/sources.list"
   "echo" done...
 "sudo apt-get install linuxbrew-wrapper"
   "echo" done...
 "sudo apt-get update -qq"
   "echo" done...
 "sudo apt-get install helix-p4d"
   "echo" done...
 "sudo apt-get install -y apt-transport-https"
   "echo" done...
 "sudo systemctl enable helix-p4dctl"
   "echo" done...
 "sudo systemctl start helix-p4dctl"
   "echo" done...
 "sudo /opt/perforce/sbin/configure-helix-p4d.sh -n perforce1 -p ssl:1666 -r /opt/perforce/servers/perforce1 -u montana -P REinforce --unicode"
   "echo" done...
 "p4 info"
   "echo" done...
 "p4 branches"
   "echo" done...
 "p4 -V" 
   "echo" done...
 "p4 -h"
   "echo" done...
 "p4 -size" 
   "echo" done...
